version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore: # Ignore Java 21 only dependency updates
      - dependency-name: "org.springframework:spring-context"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jruby:jruby"
        update-types: ["version-update:semver-major"]
      - dependency-name: "nl.jqno.equalsverifier:equalsverifier"
        update-types: ["version-update:semver-major"]
      # 15.x Informix drivers are not well-behaved
      - dependency-name: "com.ibm.informix:jdbc"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - ":children_crossing: dependencies"
    assignees:
      - "sualeh"
      - "schemacrawler"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - ":children_crossing: dependencies"
    assignees:
      - sualeh
      - schemacrawler
