# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  cassandra:
    image: cassandra:5.0.2
    container_name: cassandra
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: bind
        source: ./target
        target: /testdb
      - type: bind
        source: ./
        target: /share
