# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  db2:
    image: icr.io/db2_community/db2:11.5.9.0
    container_name: db2
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    privileged: true
    environment:
      LICENSE: accept
      DBNAME: schcrwlr
      DB2INSTANCE: books
      DB2INST1_PASSWORD: SchemaCrawler
      ARCHIVE_LOGS: false
      AUTOCONFIG: false
      TO_CREATE_SAMPLEDB: false
      REPODB: false
