# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  db2:
    image: icr.io/db2_community/db2
    container_name: db2
    privileged: true
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: SchemaCrawler
