# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    ports:
      - target: 8978
        published: 8978
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./.dbeaver
        target: /opt/cloudbeaver/workspace
    stdin_open: true
    tty: true
