# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    ports:
      - 8081:8978
    volumes:
      - type: bind
        source: ./dbeaver-workspace
        target: /opt/cloudbeaver/workspace
