# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:
  dbgate:
    image: dbgate/dbgate
    container_name: dbgate
    # restart: always
    ports:
      - 8082:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: mysql,postgres,sqlserver,oracle

      LABEL_mysql: MySql
      SERVER_mysql: mysql
      USER_mysql: root
      PASSWORD_mysql: schemacrawler
      PORT_mysql: 3306
      ENGINE_mysql: mysql@dbgate-plugin-mysql

      LABEL_postgres: PostgreSQL
      SERVER_postgres: postgres
      USER_postgres: schemacrawler
      PASSWORD_postgres: schemacrawler
      PORT_postgres: 5432
      ENGINE_postgres: postgres@dbgate-plugin-postgres

      LABEL_sqlserver: Microsoft SQL Server
      SERVER_sqlserver: sqlserver
      USER_sqlserver: SA
      PASSWORD_sqlserver: Schem#Crawl3r
      PORT_sqlserver: 1433
      AUTH_TYPE_sqlserver: sql
      ENGINE_sqlserver: mssql@dbgate-plugin-mssql

      LABEL_oracle: Oracle
      SERVER_oracle: oracle
      USER_oracle: "SYS AS SYSDBA"
      PASSWORD_oracle: test
      PORT_oracle: 1521
      DATABASE_oracle: XEPDB1
      ENGINE_oracle: oracle@dbgate-plugin-oracle

volumes:
  dbgate-data:
    driver: local
