# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  mysql:
    image: mariadb:11.6.2-noble
    container_name: mariadb
    # command: --lower_case_table_names=1 --log_bin_trust_function_creators=1
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: schemacrawler
      MARIADB_DATABASE: books
      MARIADB_USER: schemacrawler
      MARIADB_PASSWORD: schemacrawler
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
