# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  mysql:
    image: mysql:9.1.0
    container_name: mysql
    command: --lower_case_table_names=1 --log_bin_trust_function_creators=1
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: schemacrawler
      MYSQL_DATABASE: books
      MYSQL_USER: schemacrawler
      MYSQL_PASSWORD: schemacrawler
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
