# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  schemacrawler:
    image: schemacrawler/schemacrawler
    container_name: schemacrawler
    volumes:
      - type: bind
        source: ./target
        target: /home/schcrwlr/testdb
      - type: bind
        source: ./
        target: /home/schcrwlr/share
    entrypoint: ['/opt/schemacrawler/bin/schemacrawler.sh']
    command: >
      --url="jdbc:sqlite:sc.db"
      --info-level=standard
      --command=script
      --script-language=python
      --script=mermaid.py
      --output-file=share/db-schema.mmd
