# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  schemacrawler:
    image: schemacrawler/schemacrawler
    container_name: schemacrawler
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./target
        target: /home/schcrwlr/testdb
      - type: bind
        source: ./
        target: /home/schcrwlr/share
    entrypoint: /bin/bash
