# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU9-ubuntu-20.04
    container_name: sqlserver
    ports:
      - target: 1433
        published: 1433
        protocol: tcp
        mode: host
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Schem#Crawl3r
