# Copyright (c) Sualeh Fatehi
# SPDX-License-Identifier: EPL-2.0

# jdbc:trino://trino:8080/tpch/sf1?user=trino
services:
  trino:
    container_name: trino
    image: trinodb/trino:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
