services:

  adventureworks:
    image: chriseaton/adventureworks:postgres
    container_name: adventureworks
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: schemacrawler
      POSTGRES_PASSWORD: schemacrawler

  schemacrawler:
    image: schemacrawler/schemacrawler
    container_name: schemacrawler
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/schcrwlr/share
    entrypoint: /bin/bash
