services:

  sakila:
    image: sakiladb/mysql
    container_name: sakila
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host

  schemacrawler:
    image: schemacrawler/schemacrawler:extra-early-access-release
    container_name: schemacrawler
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/schcrwlr/share
    entrypoint: /bin/bash
