name: SQL Server Integration Tests

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        type: choice
        options:
          - 8
          - 21
  push:
    branches:
      - sqlserver
  schedule:
    - cron: '0 */5 * * *'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: SQL Server Integration Tests
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: maximize-build-space
      name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: '8192'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - id: restart-docker
      name: Restart Docker
      shell: bash
      run: |
        # Restart Docker to take into account additional disk space
        # https://stackoverflow.com/a/71113148/100856
        sudo systemctl stop docker
        sudo rm -rf /var/lib/docker
        sudo systemctl start docker
        echo "Docker used space:"
        sudo du -sh /var/lib/docker
        echo "Available storage:"
        df -h
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.6.1
      with:
        java-version: ${{ github.event.inputs.java_version || '8' }}
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3

# RUN DATABASE TESTS
    - id: build-test-databases
      name: Build and run SQL Server tests
      shell: bash
      run: |
        # Build and run SQL Server tests
        echo "Down SQL Server image"
        docker pull mcr.microsoft.com/mssql/server:2022-CU9-ubuntu-20.04
        echo "Build and run SQL Server tests"
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dheavydb \
          --projects schemacrawler-sqlserver \
          --also-make \
          clean package
    - id: gather-expected-results
      name: Gather expected results for failed tests
      if: always()
      shell: bash
      run: |
        # Gather expected results
        echo "Gather expected results"
        # DEBUG
        echo "Current working directory:"
        pwd
        echo "Show expected results directories:"
        find . -type d -name "unit_tests_results_output" -exec echo {} \;
        # Save expected results files
        echo "Zip expected results:"
        .github/scripts/unit-tests-results-output.sh $(realpath .)        
    - id: upload-unit-tests-results-output
      name: Upload expected results files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: expected-results-${{ matrix.database }}
        path: ./unit_tests_results_output.zip
        retention-days: 5
